version: "3"

services:
  web:
    image: nginx
    container_name: cellular_automaton
    volumes:
      - ./src:/usr/share/nginx/html
    ports:
      - "2222:80"
    environment:
      - NGINX_PORT=80